Project/urls.py
from django.contrib import admin
from django.views.debug import default_urlconf
from django.urls import path, re_path, include


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', default_urlconf),
    re_path(r'^usuario/', include('myapps.usuario.urls')),

    #url(r'^clientes/', include('myapps.clientes.urls', namespace="clientes")),
]

myapps/juicios/models.py
from django.db import models
from myapps.clientes.models import Cliente
from django.contrib.auth.models import User

# Create your models here.
class Juicio(models.Model):

	JUZGADOS_CHOICES = (
			('PAZ 1','PAZ 1'),
			('PAZ 2','PAZ 2'),
			('PAZ 3','PAZ 3'),
			('PAZ 4','PAZ 4'),
			('PAZ 5','PAZ 5'),
			('PAZ 6','PAZ 6'),
			('PAZ 7','PAZ 7'),
			('PAZ 8','PAZ 8'),
			('PAZ LAS HERAS','PAZ LAS HERAS'),
			('PAZ LUJAN','PAZ LUJAN'),
			('PAZ VILLA NUEVA','PAZ VILLA NUEVA'),
	)


	idcliente =  models.ForeignKey(Cliente,null = True, blank = True, on_delete=models.CASCADE) #Uno a muchos
	auto = models.CharField(max_length=6)
	juzgado = models.CharField(max_length=50, choices=JUZGADOS_CHOICES, default='PAZ 1')
	n_cuenta_1 = models.CharField(max_length=50, null=True, blank=True)
	n_cuenta_2 = models.CharField(max_length=50, null=True, blank=True)
	endoso = models.CharField(max_length=50)
	fecha_inicio = models.DateTimeField(max_length=15, null=True, blank=True)
	idlistado = models.IntegerField()
	idorden = models.IntegerField()
	empresa = models.CharField(max_length=50)
	estado = models.CharField(max_length=50, default = 'NORMAL')
	observacion = models.CharField(max_length=500, default = 'SIN OBSERVACION')
	created_at = models.DateTimeField(auto_now_add = True)
	update_at = models.DateTimeField(auto_now= True)
	usuario = models.CharField(max_length=50, default = User)

	def __str__(self):
		return'{} {}'.format(self.auto, self.juzgado)

class Juicio_Movimiento(models.Model):
	idjuicio = models.ForeignKey(Juicio ,null = True, blank = True, on_delete=models.CASCADE) #Uno a muchos
	auto = models.CharField(max_length=50)
	juzgado = models.CharField(max_length=50)
	tipo = models.CharField(max_length=50)
	importe = models.DecimalField(max_digits=10, decimal_places=2)
	observacion = models.CharField(max_length=500)
	created_at = models.DateTimeField(auto_now_add = True)
	update_at = models.DateTimeField(auto_now= True)
	usuario = models.CharField(max_length=50)

	def __str__(self):
		return'{} {}'.format(self.auto, self.juzgado)

class Juicio_Tarea(models.Model):
	idjuicio = models.ForeignKey(Juicio ,null = True, blank = True, on_delete=models.CASCADE) #Uno a muchos
	auto = models.CharField(max_length=50)
	juzgado = models.CharField(max_length=50)
	estado = models.CharField(max_length=50, default = 'SIN VISAR')
	visado = models.DateTimeField(max_length=15, null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add = True)
	update_at = models.DateTimeField(auto_now= True)
	usuario = models.CharField(max_length=50)

	def __str__(self):
		return'{} {}'.format(self.auto, self.juzgado)

templates/judiciales/gestor/busqueda.html
{% extends 'base/base2.html' %}

{% block content %}



<input name="q" placeholder="Escribe el nombre de una ciudad" id="buscador">

<form action="url/buscador/" method="GET">
{% csrf_token %}
...
</form>



{% endblock %}

templates/judiciales/gestor/gestor_form.html
{% extends 'base/base2.html' %}

{% block content %}

<html>
<head>
	<title>datos</title>
</head>
<body>
	<h1>MOVIMIENTOS</h1>

	<form method="POST">
		
		{% csrf_token %}

			<select id="id_tipo" name="tipo_movimiento">
				<option value="justificacion">JUSTIFICACION</option>
				<option value="honorarios">HONORARIOS</option>
			</select>
			<select name="tipo_cliente">
				<option value="1">CON CLIENTE</option>
				<option value="2">SIN CLIENTE</option>
			</select>
			<select name="juzgado">
				<option value="1">PAZ 1</option>
				<option value="2">PAZ 2</option>
				<option value="3">PAZ 3</option>
				<option value="4">PAZ 4</option>
				<option value="4">PAZ 5</option>
				<option value="6">PAZ 6</option>
				<option value="7">PAZ 7</option>
				<option value="8">PAZ 8</option>
				<option value="9">PAZ LAS HERAS</option>
				<option value="10">PAZ VILLA NUEVA</option>
				<option value="11">PAZ LUJAN</option>
			</select>

			<input type="text" name="autos" required>
			<input type="text" name="detalle" required>
			<input type="number" name="honorarios" required>
			<input type="number" name="movilidad" required>
			<input type="submit" value="Enviar">

	</form>

	<h2>{{ autos }}</h2>
	<h3>{{ detalle }}</h3>
	<h3>{{ movilidad }}</h3>
	<h3>{{ honorarios }}</h3>

<script>

function msg() {
	alert("CAROLINA HERRERA");
}


</script>

</body>
</html>



{% endblock %}

templates/judiciales/gestor/gestor_list.html
{% extends 'base/base2.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>GESTOR</td>
			<td>SALDO POR JUSTIFICAR</td>
			<td>HONORARIO A PAGAR</td>
			
		
		
		</tr>
		
	</thead>
	<tbody>
		{% if gestores %}
		{% for gestor in gestores %}
		<tr>

			<td>{{ gestor.iduser }}</td>
			<td>{{ gestor.saldo_sin_justificar }}</td>
			<td>{{ gestor.saldo_a_pagar }}</td>
			
		

		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay gestores activos</h1>
		{% endif %}
	</tbody>
</table> 

</ul>
{% endblock%}